Dev
dvergnir/js-frameworks-ca pull request #4
Opened 2023-06-05 10:53 UTC by dvergnir

Main PR

2023-06-05 11:04 UTC, Fermain requested changes
Mostly there, with a couple of changes needed. Some comments are contextual and can be resolved without any action

2023-06-05 11:04 UTC, Fermain commented on src/components/ContactForm.jsx
> +    if (formData.fullName.length < 3) {
Typically this would be done with a form validation library to ensure that it's robust - but this is fine for the CA

2023-06-05 11:04 UTC, Fermain commented on src/components/Header.jsx
> +            <Link to="/Contact" className="nav-link">
Generally speaking, lowercase page path names are preferable

2023-06-05 11:04 UTC, Fermain commented on src/components/products/style.jsx
> +export const MainContent = styled.div`
```suggestion
export const MainContent = styled.main`
```
A little more semantic

2023-06-05 11:04 UTC, Fermain commented on src/index.css
> +footer {
Why not a styled footer colocated with the component logic?

2023-06-07 13:05 UTC, dvergnir commented on src/components/ContactForm.jsx
> +      window.location.href = "/ContactSuccess";
I was not able to solve it with redirect, but it worked fine with useNavigate. I hope thats okay.

2023-06-08 10:40 UTC, Fermain requested changes
One change requested and others are comments/suggestions that you can resolve as you see fit.

Please refactor the cart items into their own component. It may seem strange to pass a function down so many levels of components, but this is fairly normal. It's called Prop Drilling

2023-06-08 10:40 UTC, Fermain commented on src/App.jsx
> +      <div>
How important is this div?

2023-06-08 10:40 UTC, Fermain commented on src/components/CartItemsList.jsx
> +            <div className="product-detail-wrapper" key={`${item.id}-${index}`}>
This is an opportunity to split off into another component. That way you are just mapping the list with a component and the file is easier to understand.

2023-06-08 10:40 UTC, Fermain commented on src/components/CartItemsList.jsx
> +      {cartItems.length === 0 ? (
I wouldn't assume that cartItems will always be initialised as an array:
```suggestion
      {cartItems && cartItems.length === 0 ? (
```

2023-06-08 13:21 UTC, merged